[2022-11-02T11:48:12.984+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_op_dag.first_task manual__2022-11-02T04:48:11.425750+00:00 [queued]>
[2022-11-02T11:48:12.990+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_python_op_dag.first_task manual__2022-11-02T04:48:11.425750+00:00 [queued]>
[2022-11-02T11:48:12.990+0700] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T11:48:12.990+0700] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-02T11:48:12.990+0700] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T11:48:12.999+0700] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): first_task> on 2022-11-02 04:48:11.425750+00:00
[2022-11-02T11:48:13.001+0700] {standard_task_runner.py:55} INFO - Started process 40536 to run task
[2022-11-02T11:48:13.003+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_python_op_dag', 'first_task', 'manual__2022-11-02T04:48:11.425750+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/python_op_dag.py', '--cfg-path', '/tmp/tmpoqaqrsju']
[2022-11-02T11:48:13.004+0700] {standard_task_runner.py:83} INFO - Job 23: Subtask first_task
[2022-11-02T11:48:13.036+0700] {task_command.py:376} INFO - Running <TaskInstance: my_python_op_dag.first_task manual__2022-11-02T04:48:11.425750+00:00 [running]> on host ginraca-VirtualBox
[2022-11-02T11:48:13.073+0700] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=my_python_op_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T04:48:11.425750+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T04:48:11.425750+00:00
[2022-11-02T11:48:13.075+0700] {xcom.py:599} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2022-11-02T11:48:13.075+0700] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/dags/python_op_dag.py", line 19, in get_time
    ti.xcom_push(key="curr_date", value=curr_date)
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2378, in xcom_push
    XCom.set(
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/models/xcom.py", line 206, in set
    value = cls.serialize_value(
  File "/home/ginraca/Documents/DatEng/airflow-tutorial/env/lib/python3.10/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2022-11-02T11:48:13.098+0700] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_op_dag, task_id=first_task, execution_date=20221102T044811, start_date=20221102T044812, end_date=20221102T044813
[2022-11-02T11:48:13.117+0700] {standard_task_runner.py:100} ERROR - Failed to execute job 23 for task first_task (Object of type datetime is not JSON serializable; 40536)
[2022-11-02T11:48:13.142+0700] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-02T11:48:13.153+0700] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
